### ISSUE TITLE
Segmentation Fault. 

### ISSUE THREAD

**Issue by silicon-ninja** [Mind-Sports-Games/Fairy-Stockfish-Rust#1]
While trying to load the config using Rust Binding this code breaks and using Fairy Stock-fish CLI it works perfectly fine. 

```rust
rsffish::loadVariantConfig(
            &fs::read_to_string(variant_file_path).expect("cannot read variant file"),
        );
        let
        rsffish::setUCIOption(&"VariantPath".to_owned(), &"data/variants.ini".to_owned());
        println!("{:?}", rsffish::availableVariants());
        Self {
            session_repo: session_repo,
            ffish_result_cache: ffish_result_cache,
        }
```

**Comment by silicon-ninja** [comment]
it works sorry.

**Comment by silicon-ninja** [comment]
Hey Lakin, While trying to get the game result using a fen the value is the range of u32. 

```rust
...
rsffish::init();
let pos = rsffish::positionFromFen(
            &"chess".to_string(),
            &"8/1Q2b1k1/2p3p1/p2p2P1/8/5PB1/PP3RK1/3r3q w - - 2 37".to_string(),
            false,
        );
println!("game result: {}", pos.gameResult());
```


### Output

```game result: 4294935296```


The info that i wanted who won and who lost. Any idea where i might have gone wrong. 

Thanks.

**Comment by lakinwecker** [comment]
Which version are you using?

Also, this seems like two different tickets, do you mind opening a new one for the second issue?

**Comment by lakinwecker** [comment]
Also, can you provide  a link to, or upload your variants.ini file so that I can use it in my tests?

**Comment by silicon-ninja** [comment]
yeah i will open up and second issue and continue on this topic. 

thanks.

**Comment by lakinwecker** [comment]
Is the segmentation fault fixed? If not, why did you close this issue?

**Comment by silicon-ninja** [comment]
the segmentation fault issue is solved. my bad it was due to init(). Thank you.

**Comment by lakinwecker** [comment]
Ah, yes. init is required right now, I'm going to reopen this. We shouldn't ever segfault in a rust lib. I'll make it panic or something instead.

**Comment by silicon-ninja** [comment]
okay sure.
